### ISSUE TITLE
Create Actions for CI CD?

### ISSUE THREAD

**Issue by alexdeveng** [barcelonajug/JBCNConf-Mobile-App#15]
* https://github.com/marketplace/actions/upload-android-release-to-play-store

**Comment by icougil** [comment]
Already done ;-) >> https://github.com/barcelonajug/JBCNConf-Mobile-App/actions

**Comment by icougil** [comment]
Sorry, I did the 1st stage, probably we need to setup the rest to be able to release APKs for Testing
